# Generated by Django 3.1.4 on 2021-03-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210322_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('shirt', 'shirt'), ('toy', 'toy'), ('short', 'short'), ('necklace', 'necklace'), ('cap', 'cap'), ('unisex', 'unisex'), ('wristwatches', 'wristwatches'), ('nightgowns', 'nightgowns')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
