# Generated by Django 3.1.4 on 2021-03-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210325_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
